### ISSUE TITLE
pg_prove --color doesn't output color when piped

### ISSUE THREAD

**Issue by dorian-marchal** [horrendo/pg_prove#1]
When I pipe `pg_prove` (for example in `cat`), colors are stripped.

I expected the `--color` flag to force color output (in the same way as `ls --color | cat`, for example).

Is there a way to force `pg_prove` to ouput colors?

My use case is executing `pg_prove` from node:

```shell
# Output color:
pg_prove --color /etc/passwd

# Doesn't output color:
pg_prove --color /etc/passwd | cat

# Doesn't output color:
node -e 'require("child_process").exec("pg_prove --color /etc/passwd", (err, res) => console.log(res));'
```

**Comment by steve-baldwin** [comment]
Hello Dorian,

My only contribution here is to provide pg_prove in a docker container. This is not an issue with the docker container but behaviour of pg_prove itself.  You could try contacting the developer of pg_prove on the mailing list - https://groups.google.com/forum/#!forum/pgtap-users

Regards,

Steve

**Comment by dorian-marchal** [comment]
Oh sorry, didn't see that, thanks for taking the time to respond. 😊
